import React from 'react'
import FormControl from '@material-ui/core/FormControl';
import InputLabel from '@material-ui/core/InputLabel';
import Select from '@material-ui/core/Select';
import MenuItem from '@material-ui/core/MenuItem';
import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles((theme) => ({
	formControl: {
		minWidth: 150
	},
}));

const languages = [
	'Abkhazian',
	'Afar',
	'Afrikaans',
	'Akan',
	'Albanian',
	'Amharic',
	'Arabic',
	'Aragonese',
	'Armenian',
	'Assamese',
	'Avaric',
	'Avestan',
	'Aymara',
	'Azerbaijani',
	'Bambara',
	'Bashkir',
	'Basque',
	'Belarusian',
	'Bengali',
	'Bihari',
	'Bislama',
	'Bosnian',
	'Breton',
	'Bulgarian',
	'Burmese',
	'Catalan',
	'Central Khmer',
	'Chamorro',
	'Chechen',
	'Chichewa',
	'Chinese',
	'Chuang',
	'Chuvash',
	'Cornish',
	'Corsican',
	'Cree',
	'Croatian',
	'Czech',
	'Danish',
	'Divehi',
	'Dutch',
	'Dzongkha',
	'English',
	'Esperanto',
	'Estonian',
	'Ewe',
	'Faroese',
	'Fijian',
	'Finnish',
	'French',
	'Fulah',
	'Gaelic',
	'Galician',
	'Ganda',
	'Georgian',
	'German',
	'Gikuyu',
	'Greek',
	'Greenlandic',
	'Guarani',
	'Gujarati',
	'Haitian',
	'Hausa',
	'Hebrew',
	'Herero',
	'Hindi',
	'Hiri Motu',
	'Hungarian',
	'Icelandic',
	'Ido',
	'Igbo',
	'Indonesian',
	'Interlingua',
	'Inuktitut',
	'Inupiaq',
	'Irish',
	'Italian',
	'Japanese',
	'Javanese',
	'Kannada',
	'Kanuri',
	'Kashmiri',
	'Kazakh',
	'Kinyarwanda',
	'Komi',
	'Kongo',
	'Korean',
	'Kwanyama',
	'Kurdish',
	'Kyrgyz',
	'Lao',
	'Latin',
	'Latvian',
	'Letzeburgesch',
	'Limburgish',
	'Lingala',
	'Lithuanian',
	'Luba-Katanga',
	'Macedonian',
	'Malagasy',
	'Malay',
	'Malayalam',
	'Maltese',
	'Manx',
	'Maori',
	'Marathi',
	'Marshallese',
	'Moldavian',
	'Mongolian',
	'Nauru',
	'Navajo',
	'Northern Ndebele',
	'Ndonga',
	'Nepali',
	'Northern Sami',
	'Norwegian',
	'Norwegian Bokmål',
	'Norwegian Nynorsk',
	'Nuosu',
	'Occitan',
	'Ojibwa',
	'Oriya',
	'Oromo',
	'Ossetian',
	'Pali',
	'Panjabi',
	'Pashto',
	'Persian',
	'Polish',
	'Portuguese',
	'Quechua',
	'Romansh',
	'Rundi',
	'Russian',
	'Samoan',
	'Sango',
	'Sanskrit',
	'Sardinian',
	'Serbian',
	'Shona',
	'Sindhi',
	'Sinhalese',
	'Slovak',
	'Slovenian',
	'Somali',
	'Southern',
	'South Ndebele',
	'Spanish, Castilian',
	'Sundanese',
	'Swahili',
	'Swati',
	'Swedish',
	'Tagalog',
	'Tahitian',
	'Tajik',
	'Tamil',
	'Tatar',
	'Telugu',
	'Thai',
	'Tibetan',
	'Tigrinya',
	'Tonga',
	'Tsonga',
	'Tswana',
	'Turkish',
	'Turkmen',
	'Twi',
	'Uighur',
	'Ukrainian',
	'Urdu',
	'Uzbek',
	'Venda',
	'Vietnamese',
	'Walloon',
	'Welsh',
	'Western Frisian',
	'Wolof',
	'Xhosa',
	'Yiddish',
	'Yoruba',
	'Zulu'
]

export default function LanguageSelector() {
	const classes = useStyles();

	const [language, setLanguage] = React.useState('');

	const handleChange = (event) => {
		setLanguage(event.target.value)
	};


	return (
		<FormControl variant="outlined" className={classes.formControl}>
			<InputLabel >Language</InputLabel>
			<Select
				value={language}
				onChange={handleChange}
				label="Language"
			>
				{languages.map(lang => (
					<MenuItem key={lang} value={lang} >
						{lang}
					</MenuItem>
				))}
			</Select>
		</FormControl >
	)
}
